project:
  output-dir: rendered
  type: website
  render:
    - reports
website:
  title: "WFBZ Descriptives"
  site-path: "wfbz_descriptives/"
  navbar: 
    left:
      - reports/main.qmd
      - reports/fema.qmd
      - reports/population.qmd
format:
  html:
    theme: cosmo
    toc: true
jupyter: wfbz    